name: Update Stock News

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

# Simplified permissions
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install feedparser
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python script.py

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public' # Tells GitHub to ONLY upload our new public folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
