name: Update Stock News

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install feedparser
          pip install -r requirements.txt

      - name: Run script
        run: python script.py
        
        - name: Commit and push
        run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add -f index.html  # Use -f to force add if ignored
        git commit -m "Auto update $(date)" || echo "No changes"
        git push origin HEAD:main
